// 🤖 AUTO-GENERATED ZERO MUTATIONS
// Generated at: 2025-07-11T06:54:06Z
//
// ⚠️  DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated. Manual changes will be overwritten.
//
// 🔧 FOR CUSTOMIZATIONS:
// Use the corresponding .custom.ts file for your custom mutations
//
// 🔄 TO REGENERATE: Run `rails generate zero:mutations`


import { getZero } from './zero-client';

// Generated TypeScript types for clients
// TypeScript interfaces for clients

/**
 * Complete Client record as stored in database
 */
export interface Client {
  name?: string| null;
  client_type?: string| null;
  created_at: number;
  updated_at: number;
  name_normalized?: string| null;
  id: string;
}

/**
 * Data required to create a new client
 * Excludes auto-generated fields (id, created_at, updated_at)
 */
export interface CreateClientData {
  name?: string| null;
  client_type?: string| null;
  name_normalized?: string| null;
}

/**
 * Data for updating an existing client
 * All fields optional, excludes auto-managed fields
 */
export interface UpdateClientData {
  name?: string| null;
  client_type?: string| null;
  name_normalized?: string| null;
}

/**
 * Standard response from mutation operations
 */
export interface ClientMutationResult {
  id: string;
}


// Generated CRUD mutations for clients

/**
 * Create a new client
 * 
 * @param data - The client data to create
 * @returns Promise resolving to the created client ID
 * 
 * @example
 * ```typescript
 * import { createClient } from './client';
 * 
 * const result = await createClient({
 *   // Add required fields here based on your schema
 * });
 * console.log('Created client with ID:', result.id);
 * ```
 */
export async function createClient(data: CreateClientData): Promise<ClientMutationResult> {
  const zero = getZero();
  
  // Generate unique ID with validation
  const id = crypto.randomUUID();
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('Failed to generate valid UUID');
  }

  const now = Date.now();

  try {
    await zero.mutate.clients.insert({
      id,
      ...data,
      created_at: now,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to create client: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Update an existing client
 * 
 * @param id - The UUID of the client to update
 * @param data - Partial client data for updates
 * @returns Promise resolving to the updated client ID
 * 
 * @example
 * ```typescript
 * import { updateClient } from './client';
 * 
 * const result = await updateClient('123e4567-e89b-12d3-a456-426614174000', {
 *   // Add fields to update
 * });
 * console.log('Updated client:', result.id);
 * ```
 */
export async function updateClient(id: string, data: UpdateClientData): Promise<ClientMutationResult> {
  const zero = getZero();
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('Client ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('Client ID must be a valid UUID');
  }

  // Validate that we have some data to update
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Update data is required - at least one field must be provided');
  }

  const now = Date.now();

  try {
    await zero.mutate.clients.update({
      id,
      ...data,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to update client: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Delete a client (permanent deletion)
 * 
 * @param id - The UUID of the client to delete
 * @returns Promise resolving to the deleted client ID
 * 
 * @example
 * ```typescript
 * import { deleteClient } from './client';
 * 
 * const result = await deleteClient('123e4567-e89b-12d3-a456-426614174000');
 * console.log('Deleted client:', result.id);
 * ```
 * 
 * @warning This is a permanent deletion and cannot be undone
 */
export async function deleteClient(id: string): Promise<ClientMutationResult> {
  const zero = getZero();
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('Client ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('Client ID must be a valid UUID');
  }

  try {
    await zero.mutate.clients.delete({
      id
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to delete client: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Create or update a client (upsert operation)
 * 
 * @param data - The client data with optional ID for update, without ID for create
 * @returns Promise resolving to the client ID (generated if creating, provided if updating)
 * 
 * @example
 * ```typescript
 * import { upsertClient } from './client';
 * 
 * // Create new client (no ID provided)
 * const newResult = await upsertClient({
 *   // Add required fields here
 * });
 * 
 * // Update existing client (ID provided)
 * const updateResult = await upsertClient({
 *   id: '123e4567-e89b-12d3-a456-426614174000',
 *   // Add fields to update
 * });
 * ```
 */
export async function upsertClient(data: (CreateClientData & { id?: string }) | (UpdateClientData & { id: string })): Promise<ClientMutationResult> {
  const zero = getZero();
  
  // Validate data is provided
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Upsert data is required');
  }

  let id: string;
  const now = Date.now();

  // If ID is provided, validate it for update operation
  if (data.id) {
    if (!data.id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('Client ID must be a valid UUID');
    }
    id = data.id;
  } else {
    // Generate new ID for create operation
    id = crypto.randomUUID();
    if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('Failed to generate valid UUID');
    }
  }

  try {
    await zero.mutate.clients.upsert({
      ...data,
      id,
      updated_at: now,
      // Set created_at only if this is a new record
      ...(data.id ? {} : { created_at: now }),
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to upsert client: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

