// 🤖 AUTO-GENERATED ZERO MUTATIONS
// Generated at: 2025-07-11T06:54:06Z
//
// ⚠️  DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated. Manual changes will be overwritten.
//
// 🔧 FOR CUSTOMIZATIONS:
// Use the corresponding .custom.ts file for your custom mutations
//
// 🔄 TO REGENERATE: Run `rails generate zero:mutations`


import { getZero } from './client';

// Generated TypeScript types for contact_methods
// TypeScript interfaces for contact_methods

/**
 * Complete ContactMethod record as stored in database
 */
export interface ContactMethod {
  value?: string| null;
  formatted_value?: string| null;
  contact_type?: number| null;
  created_at: number;
  updated_at: number;
  id: string;
  person_id?: string| null;
}

/**
 * Data required to create a new contact_method
 * Excludes auto-generated fields (id, created_at, updated_at)
 */
export interface CreateContactMethodData {
  value?: string| null;
  formatted_value?: string| null;
  contact_type?: number| null;
  person_id?: string| null;
}

/**
 * Data for updating an existing contact_method
 * All fields optional, excludes auto-managed fields
 */
export interface UpdateContactMethodData {
  value?: string| null;
  formatted_value?: string| null;
  contact_type?: number| null;
  person_id?: string| null;
}

/**
 * Standard response from mutation operations
 */
export interface ContactMethodMutationResult {
  id: string;
}


// Generated CRUD mutations for contact_methods

/**
 * Create a new contact_method
 * 
 * @param data - The contact_method data to create
 * @returns Promise resolving to the created contact_method ID
 * 
 * @example
 * ```typescript
 * import { createContactMethod } from './contact_method';
 * 
 * const result = await createContactMethod({
 *   // Add required fields here based on your schema
 * });
 * console.log('Created contact_method with ID:', result.id);
 * ```
 */
export async function createContactMethod(data: CreateContactMethodData): Promise<ContactMethodMutationResult> {
  const zero = getZero();
  
  // Generate unique ID with validation
  const id = crypto.randomUUID();
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('Failed to generate valid UUID');
  }

  const now = Date.now();

  try {
    await zero.mutate.contact_methods.insert({
      id,
      ...data,
      created_at: now,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to create contact_method: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Update an existing contact_method
 * 
 * @param id - The UUID of the contact_method to update
 * @param data - Partial contact_method data for updates
 * @returns Promise resolving to the updated contact_method ID
 * 
 * @example
 * ```typescript
 * import { updateContactMethod } from './contact_method';
 * 
 * const result = await updateContactMethod('123e4567-e89b-12d3-a456-426614174000', {
 *   // Add fields to update
 * });
 * console.log('Updated contact_method:', result.id);
 * ```
 */
export async function updateContactMethod(id: string, data: UpdateContactMethodData): Promise<ContactMethodMutationResult> {
  const zero = getZero();
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('ContactMethod ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('ContactMethod ID must be a valid UUID');
  }

  // Validate that we have some data to update
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Update data is required - at least one field must be provided');
  }

  const now = Date.now();

  try {
    await zero.mutate.contact_methods.update({
      id,
      ...data,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to update contact_method: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Delete a contact_method (permanent deletion)
 * 
 * @param id - The UUID of the contact_method to delete
 * @returns Promise resolving to the deleted contact_method ID
 * 
 * @example
 * ```typescript
 * import { deleteContactMethod } from './contact_method';
 * 
 * const result = await deleteContactMethod('123e4567-e89b-12d3-a456-426614174000');
 * console.log('Deleted contact_method:', result.id);
 * ```
 * 
 * @warning This is a permanent deletion and cannot be undone
 */
export async function deleteContactMethod(id: string): Promise<ContactMethodMutationResult> {
  const zero = getZero();
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('ContactMethod ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('ContactMethod ID must be a valid UUID');
  }

  try {
    await zero.mutate.contact_methods.delete({
      id
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to delete contact_method: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Create or update a contact_method (upsert operation)
 * 
 * @param data - The contact_method data with optional ID for update, without ID for create
 * @returns Promise resolving to the contact_method ID (generated if creating, provided if updating)
 * 
 * @example
 * ```typescript
 * import { upsertContactMethod } from './contact_method';
 * 
 * // Create new contact_method (no ID provided)
 * const newResult = await upsertContactMethod({
 *   // Add required fields here
 * });
 * 
 * // Update existing contact_method (ID provided)
 * const updateResult = await upsertContactMethod({
 *   id: '123e4567-e89b-12d3-a456-426614174000',
 *   // Add fields to update
 * });
 * ```
 */
export async function upsertContactMethod(data: (CreateContactMethodData & { id?: string }) | (UpdateContactMethodData & { id: string })): Promise<ContactMethodMutationResult> {
  const zero = getZero();
  
  // Validate data is provided
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Upsert data is required');
  }

  let id: string;
  const now = Date.now();

  // If ID is provided, validate it for update operation
  if (data.id) {
    if (!data.id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('ContactMethod ID must be a valid UUID');
    }
    id = data.id;
  } else {
    // Generate new ID for create operation
    id = crypto.randomUUID();
    if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('Failed to generate valid UUID');
    }
  }

  try {
    await zero.mutate.contact_methods.upsert({
      ...data,
      id,
      updated_at: now,
      // Set created_at only if this is a new record
      ...(data.id ? {} : { created_at: now }),
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to upsert contact_method: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

