// Zero - Complete export file
// All Zero client functionality and Epic-008 model integration
//
// Auto-generated: 2025-07-14 15:26:09 UTC
// 
// ⚠️  Do not edit this file manually - it will be regenerated
// To regenerate: rails generate zero:active_models

// Zero client initialization and management
export { initZero, getZero, getZeroAsync, getZeroState, closeZero, reinitializeZero } from './zero-client';

// Zero schema types
export { schema, type ZeroClient } from './generated-schema';

// Epic-008 models are now managed in /lib/models/ instead of legacy .generated files
// Use the Epic-008 models directly for reliable, reactive data access:
//
// import { ActivityLog, ReactiveActivityLog } from '$lib/models/activity-log';
// import { ContactMethod, ReactiveContactMethod } from '$lib/models/contact-method';
// import { Job, ReactiveJob } from '$lib/models/job';
//
// Legacy .generated.ts files have been removed as part of Epic-008 cleanup.
// This ensures consistent ReactiveRecord patterns and prevents daily regression
// from legacy fixture generators.

// Re-export Zero library types for convenience
export type { Zero } from '@rocicorp/zero';

/**
 * Epic-008 Migration Notes:
 * 
 * Before (Legacy):
 * import { User } from '$lib/zero/user.generated';
 * const usersQuery = User.all(); // Unreliable fixture generator
 * 
 * After (Epic-008):
 * import { ReactiveUser as User } from '$lib/models/reactive-user';
 * const usersQuery = User.all(); // Reliable ReactiveRecord pattern
 * 
 * Benefits:
 * - Consistent Zero.js ReactiveQuery patterns
 * - No daily regression from legacy generators  
 * - Clean separation of concerns
 * - Type-safe Epic-008 architecture
 */
