// 🤖 AUTO-GENERATED ZERO MUTATIONS
// Generated at: 2025-07-13T17:37:21Z
//
// ⚠️  DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated. Manual changes will be overwritten.
//
// 🔧 FOR CUSTOMIZATIONS:
// Use the corresponding .custom.ts file for your custom mutations
//
// 🔄 TO REGENERATE: Run `rails generate zero:mutations`


import { getZero } from './zero-client';
import { RecordInstance, type ZeroMutations } from '../record-factory/record-instance';

// Generated TypeScript types for jobs
// TypeScript interfaces for jobs

/**
 * Complete Job record as stored in database
 */
export interface Job {
  title?: string| null;
  status?: 0 | 1 | 2 | 3 | 4 | 5 | 6| null;
  priority?: 0 | 1 | 2 | 3 | 4| null;
  created_at: number;
  updated_at: number;
  description?: string| null;
  lock_version: number;
  id: string;
  client_id?: string| null;
  created_by_id?: string| null;
  due_at?: number| null;
  due_time_set: boolean;
  starts_at?: number| null;
  start_time_set: boolean;
}

/**
 * Data required to create a new job
 * Excludes auto-generated fields (id, created_at, updated_at)
 */
export interface CreateJobData {
  title?: string| null;
  status?: 0 | 1 | 2 | 3 | 4 | 5 | 6| null;
  priority?: 0 | 1 | 2 | 3 | 4| null;
  description?: string| null;
  lock_version: number;
  client_id?: string| null;
  created_by_id?: string| null;
  due_at?: number| null;
  due_time_set: boolean;
  starts_at?: number| null;
  start_time_set: boolean;
}

/**
 * Data for updating an existing job
 * All fields optional, excludes auto-managed fields
 */
export interface UpdateJobData {
  title?: string| null;
  status?: 0 | 1 | 2 | 3 | 4 | 5 | 6| null;
  priority?: 0 | 1 | 2 | 3 | 4| null;
  description?: string| null;
  lock_version?: number;
  client_id?: string| null;
  created_by_id?: string| null;
  due_at?: number| null;
  due_time_set?: boolean;
  starts_at?: number| null;
  start_time_set?: boolean;
}

/**
 * Standard response from mutation operations
 */
export interface JobMutationResult {
  id: string;
}


// Generated CRUD mutations for jobs

/**
 * Create a new job
 * 
 * @param data - The job data to create
 * @returns Promise resolving to the created job ID
 * 
 * @example
 * ```typescript
 * import { createJob } from './job';
 * 
 * const result = await createJob({
 *   // Add required fields here based on your schema
 * });
 * console.log('Created job with ID:', result.id);
 * ```
 */
export async function createJob(data: CreateJobData): Promise<JobMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate required fields
  if (data.lock_version === undefined || data.lock_version === null) throw new Error('Lock version is required');
  if (data.due_time_set === undefined || data.due_time_set === null) throw new Error('Due time set is required');
  if (data.start_time_set === undefined || data.start_time_set === null) throw new Error('Start time set is required');
  // Generate unique ID with validation
  const id = crypto.randomUUID();
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('Failed to generate valid UUID');
  }

  const now = Date.now();

  try {
    await zero.mutate.jobs.insert({
      id,
      ...data,
      created_at: now,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to create job: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Update an existing job
 * 
 * @param id - The UUID of the job to update
 * @param data - Partial job data for updates
 * @returns Promise resolving to the updated job ID
 * 
 * @example
 * ```typescript
 * import { updateJob } from './job';
 * 
 * const result = await updateJob('123e4567-e89b-12d3-a456-426614174000', {
 *   // Add fields to update
 * });
 * console.log('Updated job:', result.id);
 * ```
 */
export async function updateJob(id: string, data: UpdateJobData): Promise<JobMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('Job ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('Job ID must be a valid UUID');
  }

  // Validate that we have some data to update
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Update data is required - at least one field must be provided');
  }

  const now = Date.now();

  try {
    await zero.mutate.jobs.update({
      id,
      ...data,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to update job: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Delete a job (permanent deletion)
 * 
 * @param id - The UUID of the job to delete
 * @returns Promise resolving to the deleted job ID
 * 
 * @example
 * ```typescript
 * import { deleteJob } from './job';
 * 
 * const result = await deleteJob('123e4567-e89b-12d3-a456-426614174000');
 * console.log('Deleted job:', result.id);
 * ```
 * 
 * @warning This is a permanent deletion and cannot be undone
 */
export async function deleteJob(id: string): Promise<JobMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('Job ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('Job ID must be a valid UUID');
  }

  try {
    await zero.mutate.jobs.delete({
      id
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to delete job: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Create or update a job (upsert operation)
 * 
 * @param data - The job data with optional ID for update, without ID for create
 * @returns Promise resolving to the job ID (generated if creating, provided if updating)
 * 
 * @example
 * ```typescript
 * import { upsertJob } from './job';
 * 
 * // Create new job (no ID provided)
 * const newResult = await upsertJob({
 *   // Add required fields here
 * });
 * 
 * // Update existing job (ID provided)
 * const updateResult = await upsertJob({
 *   id: '123e4567-e89b-12d3-a456-426614174000',
 *   // Add fields to update
 * });
 * ```
 */
export async function upsertJob(data: (CreateJobData & { id?: string }) | (UpdateJobData & { id: string })): Promise<JobMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate data is provided
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Upsert data is required');
  }

  let id: string;
  const now = Date.now();

  // If ID is provided, validate it for update operation
  if (data.id) {
    if (!data.id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('Job ID must be a valid UUID');
    }
    id = data.id;
  } else {
    // Generate new ID for create operation
    id = crypto.randomUUID();
    if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('Failed to generate valid UUID');
    }
  }

  try {
    const upsertData: any = {
      ...data,
      id,
      updated_at: now,
    };
    
    // Set created_at only if this is a new record
    if (!data.id) {
      upsertData.created_at = now;
    }
    
    await zero.mutate.jobs.upsert(upsertData);

    return { id };
  } catch (error) {
    throw new Error(`Failed to upsert job: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}



// ActiveRecord-style instance class for individual job records

/**
 * ActiveRecord-style instance class for Job
 * Provides Rails-compatible instance methods: update(), delete(), restore()
 * 
 * Generated from Rails model: Job
 * 
 * @example
 * ```typescript
 * const job = Job.find('123').current;
 * if (job) {
 *   const instance = new JobInstance(job);
 *   await instance.update({ title: 'Updated Title', status: open });
 *   await instance.delete(); // Permanent delete
 *   
 * }
 * ```
 */
export class JobInstance extends RecordInstance<Job> {
  protected mutations: ZeroMutations<Job> = {
    update: async (id: string, data: Partial<Job>) => {
      return await updateJob(id, data as UpdateJobData);
    },
    delete: async (id: string) => {
      return await deleteJob(id);
    }
  };

  constructor(data: Job) {
    super(data);
  }



/**
 * Convenience method for updating status
 * Generated from Rails enum
 */
async updateStatus(status: string): Promise<{ id: string }> {
  return await this.update({ status: status as any });
}



  /**
   * Rails-compatible inspect method for debugging
   */
  inspect(): string {
    return `#<JobInstance id: ${this.data.id}, title: "${(this.data as any).title}">`;
  }
}

/**
 * Factory function to create JobInstance from data
 * Used internally by ReactiveRecord and ActiveRecord
 */
export function createJobInstance(data: Job): JobInstance {
  return new JobInstance(data);
}


// Generated ActiveRecord-style queries for jobs


// Zero reactive query wrapper using materialize() for active queries
// This creates active queries that populate Zero's cache and stay synchronized
function createReactiveQuery<T>(queryBuilder: any, defaultValue: T) {
  let current = defaultValue;
  let resultType: 'loading' | 'success' | 'error' = 'loading';
  let error: Error | null = null;
  let view: any = null;
  let retryCount = 0;
  const maxRetries = 3;

  const execute = async () => {
    try {
      resultType = 'loading';
      
      // Check if Zero is ready
      const zero = getZero();
      if (!zero) {
        setTimeout(() => execute(), 100);
        return;
      }
      
      // Create active query using materialize()
      view = queryBuilder.materialize();
      const result = await view.data;
      
      // If result is null and we haven't retried much, try again
      if ((result === null || result === undefined) && retryCount < maxRetries) {
        retryCount++;
        setTimeout(() => execute(), 500);
        return;
      }
      
      current = result || defaultValue;
      resultType = 'success';
      error = null;
      retryCount = 0;
    } catch (err) {
      error = err instanceof Error ? err : new Error('Unknown error');
      resultType = 'error';
      
      // Retry on error if we haven't exceeded max retries
      if (retryCount < maxRetries) {
        retryCount++;
        setTimeout(() => execute(), 1000);
      }
    }
  };

  // Execute after a small delay to let Zero initialize
  setTimeout(() => execute(), 100);

  return {
    get current() { return current; },
    get value() { return current; },
    get resultType() { return resultType; },
    get error() { return error; },
    refresh: execute,
    destroy: () => view?.destroy()
  };
}

/**
 * ActiveRecord-style query interface for jobs
 * Provides offline-capable queries that work with Zero's local database
 */
export const Job = {
  /**
   * Find a single job by ID
   * @param id - The UUID of the job
   * @returns Zero query result with the job or null
   * 
   * @example
   * ```typescript
   * const job = Job.find('123e4567-e89b-12d3-a456-426614174000');
   * console.log(job.current); // The job object or null
   * ```
   */
  find(id: string) {
    const zero = getZero();
    if (!zero) return { current: null, value: null, resultType: 'loading' as const, error: null };
    
    return createReactiveQuery(
      zero.query.jobs.where('id', id).one(),
      null as Job | null
    );
  },

  /**
   * Get all jobs (includes discarded records like Rails Task.all)
   * @returns Zero query result with array of jobs
   * 
   * @example
   * ```typescript
   * const allJobs = Job.all();
   * console.log(allJobs.current); // Array of jobs including discarded
   * ```
   */
  all() {
    const zero = getZero();
    if (!zero) return { current: [], value: [], resultType: 'loading' as const, error: null };
    
    return createReactiveQuery(
      zero.query.jobs.orderBy('created_at', 'desc'),
      [] as Job[]
    );
  },

  /**
   * Find jobs matching conditions (includes discarded)
   * @param conditions - Object with field/value pairs to match
   * @returns Zero query result with array of matching jobs
   * 
   * @example
   * ```typescript
   * const activeJobs = Job.where({ status: 'active' });
   * const clientJobs = Job.where({ client_id: 'some-uuid' });
   * ```
   */
  where(conditions: Partial<Job>) {
    const zero = getZero();
    if (!zero) return { current: [], value: [], resultType: 'loading' as const, error: null };
    
    let query = zero.query.jobs;
    
    Object.entries(conditions).forEach(([key, value]) => {
      if (value !== undefined && value !== null) {
        query = query.where(key as any, value);
      }
    });
    
    return createReactiveQuery(
      query.orderBy('created_at', 'desc'),
      [] as Job[]
    );
  }
};

