// 🤖 AUTO-GENERATED ZERO MUTATIONS
// Generated at: 2025-07-14T02:59:43Z
//
// ⚠️  DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated. Manual changes will be overwritten.
//
// 🔧 FOR CUSTOMIZATIONS:
// Use the corresponding .custom.ts file for your custom mutations
//
// 🔄 TO REGENERATE: Run `rails generate zero:mutations`


import { getZero } from './zero-client';
import { RecordInstance, type ZeroMutations } from '../models/base/record-instance';

// Generated TypeScript types for job_targets
// TypeScript interfaces for job_targets

/**
 * Complete JobTarget record as stored in database
 */
export interface JobTarget {
  target_type: string;
  status?: string| null;
  instance_number: number;
  reason?: string| null;
  created_at: number;
  updated_at: number;
  id: string;
  job_id?: string| null;
  target_id?: string| null;
}

/**
 * Data required to create a new job_target
 * Excludes auto-generated fields (id, created_at, updated_at)
 */
export interface CreateJobTargetData {
  target_type: string;
  status?: string| null;
  instance_number: number;
  reason?: string| null;
  job_id?: string| null;
  target_id?: string| null;
}

/**
 * Data for updating an existing job_target
 * All fields optional, excludes auto-managed fields
 */
export interface UpdateJobTargetData {
  target_type?: string;
  status?: string| null;
  instance_number?: number;
  reason?: string| null;
  job_id?: string| null;
  target_id?: string| null;
}

/**
 * Standard response from mutation operations
 */
export interface JobTargetMutationResult {
  id: string;
}


// Generated CRUD mutations for job_targets

/**
 * Create a new job_target
 * 
 * @param data - The job_target data to create
 * @returns Promise resolving to the created job_target ID
 * 
 * @example
 * ```typescript
 * import { createJobTarget } from './job_target';
 * 
 * const result = await createJobTarget({
 *   // Add required fields here based on your schema
 * });
 * console.log('Created job_target with ID:', result.id);
 * ```
 */
export async function createJobTarget(data: CreateJobTargetData): Promise<JobTargetMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate required fields
  if (!data.target_type?.trim()) throw new Error('Target type is required');
  if (data.instance_number === undefined || data.instance_number === null) throw new Error('Instance number is required');
  // Generate unique ID with validation
  const id = crypto.randomUUID();
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('Failed to generate valid UUID');
  }

  const now = Date.now();

  try {
    await zero.mutate.job_targets.insert({
      id,
      ...data,
      created_at: now,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to create job_target: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Update an existing job_target
 * 
 * @param id - The UUID of the job_target to update
 * @param data - Partial job_target data for updates
 * @returns Promise resolving to the updated job_target ID
 * 
 * @example
 * ```typescript
 * import { updateJobTarget } from './job_target';
 * 
 * const result = await updateJobTarget('123e4567-e89b-12d3-a456-426614174000', {
 *   // Add fields to update
 * });
 * console.log('Updated job_target:', result.id);
 * ```
 */
export async function updateJobTarget(id: string, data: UpdateJobTargetData): Promise<JobTargetMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('JobTarget ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('JobTarget ID must be a valid UUID');
  }

  // Validate that we have some data to update
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Update data is required - at least one field must be provided');
  }

  const now = Date.now();

  try {
    await zero.mutate.job_targets.update({
      id,
      ...data,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to update job_target: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Delete a job_target (permanent deletion)
 * 
 * @param id - The UUID of the job_target to delete
 * @returns Promise resolving to the deleted job_target ID
 * 
 * @example
 * ```typescript
 * import { deleteJobTarget } from './job_target';
 * 
 * const result = await deleteJobTarget('123e4567-e89b-12d3-a456-426614174000');
 * console.log('Deleted job_target:', result.id);
 * ```
 * 
 * @warning This is a permanent deletion and cannot be undone
 */
export async function deleteJobTarget(id: string): Promise<JobTargetMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('JobTarget ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('JobTarget ID must be a valid UUID');
  }

  try {
    await zero.mutate.job_targets.delete({
      id
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to delete job_target: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Create or update a job_target (upsert operation)
 * 
 * @param data - The job_target data with optional ID for update, without ID for create
 * @returns Promise resolving to the job_target ID (generated if creating, provided if updating)
 * 
 * @example
 * ```typescript
 * import { upsertJobTarget } from './job_target';
 * 
 * // Create new job_target (no ID provided)
 * const newResult = await upsertJobTarget({
 *   // Add required fields here
 * });
 * 
 * // Update existing job_target (ID provided)
 * const updateResult = await upsertJobTarget({
 *   id: '123e4567-e89b-12d3-a456-426614174000',
 *   // Add fields to update
 * });
 * ```
 */
export async function upsertJobTarget(data: (CreateJobTargetData & { id?: string }) | (UpdateJobTargetData & { id: string })): Promise<JobTargetMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate data is provided
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Upsert data is required');
  }

  let id: string;
  const now = Date.now();

  // If ID is provided, validate it for update operation
  if (data.id) {
    if (!data.id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('JobTarget ID must be a valid UUID');
    }
    id = data.id;
  } else {
    // Generate new ID for create operation
    id = crypto.randomUUID();
    if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('Failed to generate valid UUID');
    }
  }

  try {
    const upsertData: any = {
      ...data,
      id,
      updated_at: now,
    };
    
    // Set created_at only if this is a new record
    if (!data.id) {
      upsertData.created_at = now;
    }
    
    await zero.mutate.job_targets.upsert(upsertData);

    return { id };
  } catch (error) {
    throw new Error(`Failed to upsert job_target: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}



// ActiveRecord-style instance class for individual job_target records

/**
 * ActiveRecord-style instance class for JobTarget
 * Provides Rails-compatible instance methods: update(), delete(), restore()
 * 
 * Generated from Rails model: JobTarget
 * 
 * @example
 * ```typescript
 * const job_target = JobTarget.find('123').current;
 * if (job_target) {
 *   const instance = new JobTargetInstance(job_target);
 *   await instance.update({ // fields to update });
 *   await instance.delete(); // Permanent delete
 *   
 * }
 * ```
 */
export class JobTargetInstance extends RecordInstance<JobTarget> {
  protected mutations: ZeroMutations<JobTarget> = {
    update: async (id: string, data: Partial<JobTarget>) => {
      return await updateJobTarget(id, data as UpdateJobTargetData);
    },
    delete: async (id: string) => {
      return await deleteJobTarget(id);
    }
  };

  constructor(data: JobTarget) {
    super(data);
  }





  /**
   * Rails-compatible inspect method for debugging
   */
  inspect(): string {
    return `#<JobTargetInstance id: ${this.data.id}>`;
  }
}

/**
 * Factory function to create JobTargetInstance from data
 * Used internally by ReactiveRecord and ActiveRecord
 */
export function createJobTargetInstance(data: JobTarget): JobTargetInstance {
  return new JobTargetInstance(data);
}


// Generated ActiveRecord-style queries for job_targets


// Zero reactive query wrapper using materialize() for active queries
// This creates active queries that populate Zero's cache and stay synchronized
function createReactiveQuery<T>(queryBuilder: any, defaultValue: T) {
  let current = defaultValue;
  let resultType: 'loading' | 'success' | 'error' = 'loading';
  let error: Error | null = null;
  let view: any = null;
  let retryCount = 0;
  const maxRetries = 3;

  const execute = async () => {
    try {
      resultType = 'loading';
      
      // Check if Zero is ready
      const zero = getZero();
      if (!zero) {
        setTimeout(() => execute(), 100);
        return;
      }
      
      // Create active query using materialize()
      view = queryBuilder.materialize();
      const result = await view.data;
      
      // If result is null and we haven't retried much, try again
      if ((result === null || result === undefined) && retryCount < maxRetries) {
        retryCount++;
        setTimeout(() => execute(), 500);
        return;
      }
      
      current = result || defaultValue;
      resultType = 'success';
      error = null;
      retryCount = 0;
    } catch (err) {
      error = err instanceof Error ? err : new Error('Unknown error');
      resultType = 'error';
      
      // Retry on error if we haven't exceeded max retries
      if (retryCount < maxRetries) {
        retryCount++;
        setTimeout(() => execute(), 1000);
      }
    }
  };

  // Execute after a small delay to let Zero initialize
  setTimeout(() => execute(), 100);

  return {
    get current() { return current; },
    get value() { return current; },
    get resultType() { return resultType; },
    get error() { return error; },
    refresh: execute,
    destroy: () => view?.destroy()
  };
}

/**
 * ActiveRecord-style query interface for job_targets
 * Provides offline-capable queries that work with Zero's local database
 */
export const JobTarget = {
  /**
   * Find a single job_target by ID
   * @param id - The UUID of the job_target
   * @returns Zero query result with the job_target or null
   * 
   * @example
   * ```typescript
   * const job_target = JobTarget.find('123e4567-e89b-12d3-a456-426614174000');
   * console.log(job_target.current); // The job_target object or null
   * ```
   */
  find(id: string) {
    const zero = getZero();
    if (!zero) return { current: null, value: null, resultType: 'loading' as const, error: null };
    
    return createReactiveQuery(
      zero.query.job_targets.where('id', id).one(),
      null as JobTarget | null
    );
  },

  /**
   * Get all job_targets (includes discarded records like Rails Task.all)
   * @returns Zero query result with array of job_targets
   * 
   * @example
   * ```typescript
   * const allJobTargets = JobTarget.all();
   * console.log(allJobTargets.current); // Array of job_targets including discarded
   * ```
   */
  all() {
    const zero = getZero();
    if (!zero) return { current: [], value: [], resultType: 'loading' as const, error: null };
    
    return createReactiveQuery(
      zero.query.job_targets.orderBy('created_at', 'desc'),
      [] as JobTarget[]
    );
  },

  /**
   * Find job_targets matching conditions (includes discarded)
   * @param conditions - Object with field/value pairs to match
   * @returns Zero query result with array of matching job_targets
   * 
   * @example
   * ```typescript
   * const activeJobTargets = JobTarget.where({ status: 'active' });
   * const clientJobs = JobTarget.where({ client_id: 'some-uuid' });
   * ```
   */
  where(conditions: Partial<JobTarget>) {
    const zero = getZero();
    if (!zero) return { current: [], value: [], resultType: 'loading' as const, error: null };
    
    let query = zero.query.job_targets;
    
    Object.entries(conditions).forEach(([key, value]) => {
      if (value !== undefined && value !== null) {
        query = query.where(key as any, value);
      }
    });
    
    return createReactiveQuery(
      query.orderBy('created_at', 'desc'),
      [] as JobTarget[]
    );
  }
};

