// 🤖 AUTO-GENERATED ZERO MUTATIONS
// Generated at: 2025-07-14T05:31:26Z
//
// ⚠️  DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated. Manual changes will be overwritten.
//
// 🔧 FOR CUSTOMIZATIONS:
// Use the corresponding .custom.ts file for your custom mutations
//
// 🔄 TO REGENERATE: Run `rails generate zero:mutations`


import { getZero } from './zero-client';
import { RecordInstance, type ZeroMutations } from '../models/base/record-instance';

// Generated TypeScript types for scheduled_date_times
// TypeScript interfaces for scheduled_date_times

/**
 * Complete ScheduledDateTime record as stored in database
 */
export interface ScheduledDateTime {
  schedulable_type: string;
  scheduled_type: string;
  notes?: string| null;
  created_at: number;
  updated_at: number;
  id: string;
  schedulable_id?: string| null;
  scheduled_at?: number| null;
  scheduled_time_set: boolean;
}

/**
 * Data required to create a new scheduled_date_time
 * Excludes auto-generated fields (id, created_at, updated_at)
 */
export interface CreateScheduledDateTimeData {
  schedulable_type: string;
  scheduled_type: string;
  notes?: string| null;
  schedulable_id?: string| null;
  scheduled_at?: number| null;
  scheduled_time_set: boolean;
}

/**
 * Data for updating an existing scheduled_date_time
 * All fields optional, excludes auto-managed fields
 */
export interface UpdateScheduledDateTimeData {
  schedulable_type?: string;
  scheduled_type?: string;
  notes?: string| null;
  schedulable_id?: string| null;
  scheduled_at?: number| null;
  scheduled_time_set?: boolean;
}

/**
 * Standard response from mutation operations
 */
export interface ScheduledDateTimeMutationResult {
  id: string;
}


// Generated CRUD mutations for scheduled_date_times

/**
 * Create a new scheduled_date_time
 * 
 * @param data - The scheduled_date_time data to create
 * @returns Promise resolving to the created scheduled_date_time ID
 * 
 * @example
 * ```typescript
 * import { createScheduledDateTime } from './scheduled_date_time';
 * 
 * const result = await createScheduledDateTime({
 *   // Add required fields here based on your schema
 * });
 * console.log('Created scheduled_date_time with ID:', result.id);
 * ```
 */
export async function createScheduledDateTime(data: CreateScheduledDateTimeData): Promise<ScheduledDateTimeMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate required fields
  if (!data.schedulable_type?.trim()) throw new Error('Schedulable type is required');
  if (!data.scheduled_type?.trim()) throw new Error('Scheduled type is required');
  if (data.scheduled_time_set === undefined || data.scheduled_time_set === null) throw new Error('Scheduled time set is required');
  // Generate unique ID with validation
  const id = crypto.randomUUID();
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('Failed to generate valid UUID');
  }

  const now = Date.now();

  try {
    await zero.mutate.scheduled_date_times.insert({
      id,
      ...data,
      created_at: now,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to create scheduled_date_time: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Update an existing scheduled_date_time
 * 
 * @param id - The UUID of the scheduled_date_time to update
 * @param data - Partial scheduled_date_time data for updates
 * @returns Promise resolving to the updated scheduled_date_time ID
 * 
 * @example
 * ```typescript
 * import { updateScheduledDateTime } from './scheduled_date_time';
 * 
 * const result = await updateScheduledDateTime('123e4567-e89b-12d3-a456-426614174000', {
 *   // Add fields to update
 * });
 * console.log('Updated scheduled_date_time:', result.id);
 * ```
 */
export async function updateScheduledDateTime(id: string, data: UpdateScheduledDateTimeData): Promise<ScheduledDateTimeMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('ScheduledDateTime ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('ScheduledDateTime ID must be a valid UUID');
  }

  // Validate that we have some data to update
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Update data is required - at least one field must be provided');
  }

  const now = Date.now();

  try {
    await zero.mutate.scheduled_date_times.update({
      id,
      ...data,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to update scheduled_date_time: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Delete a scheduled_date_time (permanent deletion)
 * 
 * @param id - The UUID of the scheduled_date_time to delete
 * @returns Promise resolving to the deleted scheduled_date_time ID
 * 
 * @example
 * ```typescript
 * import { deleteScheduledDateTime } from './scheduled_date_time';
 * 
 * const result = await deleteScheduledDateTime('123e4567-e89b-12d3-a456-426614174000');
 * console.log('Deleted scheduled_date_time:', result.id);
 * ```
 * 
 * @warning This is a permanent deletion and cannot be undone
 */
export async function deleteScheduledDateTime(id: string): Promise<ScheduledDateTimeMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('ScheduledDateTime ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('ScheduledDateTime ID must be a valid UUID');
  }

  try {
    await zero.mutate.scheduled_date_times.delete({
      id
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to delete scheduled_date_time: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Create or update a scheduled_date_time (upsert operation)
 * 
 * @param data - The scheduled_date_time data with optional ID for update, without ID for create
 * @returns Promise resolving to the scheduled_date_time ID (generated if creating, provided if updating)
 * 
 * @example
 * ```typescript
 * import { upsertScheduledDateTime } from './scheduled_date_time';
 * 
 * // Create new scheduled_date_time (no ID provided)
 * const newResult = await upsertScheduledDateTime({
 *   // Add required fields here
 * });
 * 
 * // Update existing scheduled_date_time (ID provided)
 * const updateResult = await upsertScheduledDateTime({
 *   id: '123e4567-e89b-12d3-a456-426614174000',
 *   // Add fields to update
 * });
 * ```
 */
export async function upsertScheduledDateTime(data: (CreateScheduledDateTimeData & { id?: string }) | (UpdateScheduledDateTimeData & { id: string })): Promise<ScheduledDateTimeMutationResult> {
  const zero = getZero();
  if (!zero) {
    throw new Error('Zero client not initialized. Please ensure Zero is properly set up.');
  }
  
  // Validate data is provided
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Upsert data is required');
  }

  let id: string;
  const now = Date.now();

  // If ID is provided, validate it for update operation
  if (data.id) {
    if (!data.id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('ScheduledDateTime ID must be a valid UUID');
    }
    id = data.id;
  } else {
    // Generate new ID for create operation
    id = crypto.randomUUID();
    if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('Failed to generate valid UUID');
    }
  }

  try {
    const upsertData: any = {
      ...data,
      id,
      updated_at: now,
    };
    
    // Set created_at only if this is a new record
    if (!data.id) {
      upsertData.created_at = now;
    }
    
    await zero.mutate.scheduled_date_times.upsert(upsertData);

    return { id };
  } catch (error) {
    throw new Error(`Failed to upsert scheduled_date_time: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}



// ActiveRecord-style instance class for individual scheduled_date_time records

/**
 * ActiveRecord-style instance class for ScheduledDateTime
 * Provides Rails-compatible instance methods: update(), delete(), restore()
 * 
 * Generated from Rails model: ScheduledDateTime
 * 
 * @example
 * ```typescript
 * const scheduled_date_time = ScheduledDateTime.find('123').current;
 * if (scheduled_date_time) {
 *   const instance = new ScheduledDateTimeInstance(scheduled_date_time);
 *   await instance.update({ // fields to update });
 *   await instance.delete(); // Permanent delete
 *   
 * }
 * ```
 */
export class ScheduledDateTimeInstance extends RecordInstance<ScheduledDateTime> {
  protected mutations: ZeroMutations<ScheduledDateTime> = {
    update: async (id: string, data: Partial<ScheduledDateTime>) => {
      return await updateScheduledDateTime(id, data as UpdateScheduledDateTimeData);
    },
    delete: async (id: string) => {
      return await deleteScheduledDateTime(id);
    }
  };

  constructor(data: ScheduledDateTime) {
    super(data);
  }





  /**
   * Rails-compatible inspect method for debugging
   */
  inspect(): string {
    return `#<ScheduledDateTimeInstance id: ${this.data.id}>`;
  }
}

/**
 * Factory function to create ScheduledDateTimeInstance from data
 * Used internally by ReactiveRecord and ActiveRecord
 */
export function createScheduledDateTimeInstance(data: ScheduledDateTime): ScheduledDateTimeInstance {
  return new ScheduledDateTimeInstance(data);
}


// Generated ActiveRecord-style queries for scheduled_date_times


// Zero reactive query wrapper using materialize() for active queries
// This creates active queries that populate Zero's cache and stay synchronized
function createReactiveQuery<T>(queryBuilder: any, defaultValue: T) {
  let current = defaultValue;
  let resultType: 'loading' | 'success' | 'error' = 'loading';
  let error: Error | null = null;
  let view: any = null;
  let retryCount = 0;
  const maxRetries = 3;

  const execute = async () => {
    try {
      resultType = 'loading';
      
      // Check if Zero is ready
      const zero = getZero();
      if (!zero) {
        setTimeout(() => execute(), 100);
        return;
      }
      
      // Create active query using materialize()
      view = queryBuilder.materialize();
      const result = await view.data;
      
      // If result is null and we haven't retried much, try again
      if ((result === null || result === undefined) && retryCount < maxRetries) {
        retryCount++;
        setTimeout(() => execute(), 500);
        return;
      }
      
      current = result || defaultValue;
      resultType = 'success';
      error = null;
      retryCount = 0;
    } catch (err) {
      error = err instanceof Error ? err : new Error('Unknown error');
      resultType = 'error';
      
      // Retry on error if we haven't exceeded max retries
      if (retryCount < maxRetries) {
        retryCount++;
        setTimeout(() => execute(), 1000);
      }
    }
  };

  // Execute after a small delay to let Zero initialize
  setTimeout(() => execute(), 100);

  return {
    get current() { return current; },
    get value() { return current; },
    get resultType() { return resultType; },
    get error() { return error; },
    refresh: execute,
    destroy: () => view?.destroy()
  };
}

/**
 * ActiveRecord-style query interface for scheduled_date_times
 * Provides offline-capable queries that work with Zero's local database
 */
export const ScheduledDateTime = {
  /**
   * Find a single scheduled_date_time by ID
   * @param id - The UUID of the scheduled_date_time
   * @returns Zero query result with the scheduled_date_time or null
   * 
   * @example
   * ```typescript
   * const scheduled_date_time = ScheduledDateTime.find('123e4567-e89b-12d3-a456-426614174000');
   * console.log(scheduled_date_time.current); // The scheduled_date_time object or null
   * ```
   */
  find(id: string) {
    const zero = getZero();
    if (!zero) return { current: null, value: null, resultType: 'loading' as const, error: null };
    
    return createReactiveQuery(
      zero.query.scheduled_date_times.where('id', id).one(),
      null as ScheduledDateTime | null
    );
  },

  /**
   * Get all scheduled_date_times (includes discarded records like Rails Task.all)
   * @returns Zero query result with array of scheduled_date_times
   * 
   * @example
   * ```typescript
   * const allScheduledDateTimes = ScheduledDateTime.all();
   * console.log(allScheduledDateTimes.current); // Array of scheduled_date_times including discarded
   * ```
   */
  all() {
    const zero = getZero();
    if (!zero) return { current: [], value: [], resultType: 'loading' as const, error: null };
    
    return createReactiveQuery(
      zero.query.scheduled_date_times.orderBy('created_at', 'desc'),
      [] as ScheduledDateTime[]
    );
  },

  /**
   * Find scheduled_date_times matching conditions (includes discarded)
   * @param conditions - Object with field/value pairs to match
   * @returns Zero query result with array of matching scheduled_date_times
   * 
   * @example
   * ```typescript
   * const activeScheduledDateTimes = ScheduledDateTime.where({ status: 'active' });
   * const clientJobs = ScheduledDateTime.where({ client_id: 'some-uuid' });
   * ```
   */
  where(conditions: Partial<ScheduledDateTime>) {
    const zero = getZero();
    if (!zero) return { current: [], value: [], resultType: 'loading' as const, error: null };
    
    let query = zero.query.scheduled_date_times;
    
    Object.entries(conditions).forEach(([key, value]) => {
      if (value !== undefined && value !== null) {
        query = query.where(key as any, value);
      }
    });
    
    return createReactiveQuery(
      query.orderBy('created_at', 'desc'),
      [] as ScheduledDateTime[]
    );
  }
};

