// Generated TypeScript Types from Rails Schema
// Generated at: 2025-08-04T01:53:46Z
// DO NOT EDIT - This file is automatically generated

export interface ActivityLog {
  action?: string;
  loggable_type: string;
  metadata?: any;
  created_at: string;
  updated_at: string;
  id: string;
  user_id?: string;
  client_id?: string;
  job_id?: string;
  loggable_id?: string;
}

export interface ContactMethod {
  value?: string;
  formatted_value?: string;
  created_at: string;
  updated_at: string;
  id: string;
  person_id?: string;
  contact_type: string;
}

export interface Job {
  title?: string;
  created_at: string;
  updated_at: string;
  description?: string;
  lock_version: number;
  id: string;
  client_id?: string;
  due_at?: string;
  due_time_set: boolean;
  starts_at?: string;
  start_time_set: boolean;
  status: string;
  priority: string;
}

export interface Client {
  name?: string;
  created_at: string;
  updated_at: string;
  name_normalized?: string;
  id: string;
  client_type: string;
}

export interface Device {
  name?: string;
  model?: string;
  serial_number?: string;
  location?: string;
  notes?: string;
  created_at: string;
  updated_at: string;
  id: string;
  client_id?: string;
  person_id?: string;
}

export interface JobAssignment {
  created_at: string;
  updated_at: string;
  id: string;
  job_id?: string;
  user_id?: string;
}

export interface JobPerson {
  created_at: string;
  updated_at: string;
  id: string;
  job_id?: string;
  person_id?: string;
}

export interface PeopleGroup {
  id: string;
  name: string;
  is_department: boolean;
  client_id: string;
  created_at: string;
  updated_at: string;
}

export interface PeopleGroupMembership {
  id: string;
  person_id: string;
  people_group_id: string;
  created_at: string;
  updated_at: string;
}

export interface Note {
  notable_type: string;
  content?: string;
  created_at: string;
  updated_at: string;
  metadata?: any;
  id: string;
  user_id?: string;
  notable_id?: string;
}

export interface JobTarget {
  target_type: string;
  status?: string;
  instance_number: number;
  reason?: string;
  created_at: string;
  updated_at: string;
  id: string;
  job_id?: string;
  target_id?: string;
}

export interface ScheduledDateTime {
  schedulable_type: string;
  scheduled_type: string;
  notes?: string;
  created_at: string;
  updated_at: string;
  id: string;
  schedulable_id?: string;
  scheduled_at?: string;
  scheduled_time_set: boolean;
}

export interface ScheduledDateTimeUser {
  created_at: string;
  updated_at: string;
  id: string;
  scheduled_date_time_id?: string;
  user_id?: string;
}

export interface Person {
  name?: string;
  created_at: string;
  updated_at: string;
  id: string;
  client_id?: string;
  name_preferred?: string;
  name_pronunciation_hint?: string;
  is_active?: boolean;
  title?: string;
}

export interface Task {
  title?: string;
  position: number;
  created_at: string;
  updated_at: string;
  subtasks_count?: number;
  reordered_at?: string;
  lock_version: number;
  applies_to_all_targets: boolean;
  id: string;
  job_id?: string;
  assigned_to_id?: string;
  parent_id?: string;
  discarded_at?: string;
  status: string;
  repositioned_after_id?: string;
  position_finalized: boolean;
  repositioned_to_top: boolean;
}

export interface User {
  name?: string;
  email?: string;
  created_at: string;
  updated_at: string;
  password_digest?: string;
  resort_tasks_on_status_change: boolean;
  id: string;
  role: string;
  short_name?: string;
}

// Union types for easier usage
export type TableNames =
  | 'activity_logs'
  | 'contact_methods'
  | 'jobs'
  | 'clients'
  | 'devices'
  | 'job_assignments'
  | 'job_people'
  | 'people_groups'
  | 'people_group_memberships'
  | 'notes'
  | 'job_targets'
  | 'scheduled_date_times'
  | 'scheduled_date_time_users'
  | 'people'
  | 'tasks'
  | 'users';
export type ModelNames =
  | 'activity_log'
  | 'contact_method'
  | 'job'
  | 'client'
  | 'device'
  | 'job_assignment'
  | 'job_person'
  | 'people_group'
  | 'people_group_membership'
  | 'note'
  | 'job_target'
  | 'scheduled_date_time'
  | 'scheduled_date_time_user'
  | 'person'
  | 'task'
  | 'user';
