// Generated TypeScript Types from Rails Schema
// Generated at: 2025-07-11T07:18:07Z
// DO NOT EDIT - This file is automatically generated

export interface ActivityLog {
  action?: string;
  loggable_type: string;
  metadata?: any;
  created_at: string;
  updated_at: string;
  id: string;
  user_id?: string;
  client_id?: string;
  job_id?: string;
  loggable_id?: string;
}


export interface ContactMethod {
  value?: string;
  formatted_value?: string;
  contact_type?: number;
  created_at: string;
  updated_at: string;
  id: string;
  person_id?: string;
}


export interface Job {
  title?: string;
  status?: number;
  priority?: number;
  created_at: string;
  updated_at: string;
  description?: string;
  lock_version: number;
  id: string;
  client_id?: string;
  created_by_id?: string;
  due_at?: string;
  due_time_set: boolean;
  starts_at?: string;
  start_time_set: boolean;
}


export interface Client {
  name?: string;
  client_type?: string;
  created_at: string;
  updated_at: string;
  name_normalized?: string;
  id: string;
}


export interface Device {
  name?: string;
  model?: string;
  serial_number?: string;
  location?: string;
  notes?: string;
  created_at: string;
  updated_at: string;
  id: string;
  client_id?: string;
  person_id?: string;
}


export interface JobAssignment {
  created_at: string;
  updated_at: string;
  id: string;
  job_id?: string;
  user_id?: string;
}


export interface JobPerson {
  created_at: string;
  updated_at: string;
  id: string;
  job_id?: string;
  person_id?: string;
}


export interface JobTarget {
  target_type: string;
  status?: string;
  instance_number: number;
  reason?: string;
  created_at: string;
  updated_at: string;
  id: string;
  job_id?: string;
  target_id?: string;
}


export interface Note {
  notable_type: string;
  content?: string;
  created_at: string;
  updated_at: string;
  metadata?: any;
  id: string;
  user_id?: string;
  notable_id?: string;
}


export interface Person {
  name?: string;
  notes?: string;
  created_at: string;
  updated_at: string;
  id: string;
  client_id?: string;
}


export interface ScheduledDateTimeUser {
  created_at: string;
  updated_at: string;
  id: string;
  scheduled_date_time_id?: string;
  user_id?: string;
}


export interface ScheduledDateTime {
  schedulable_type: string;
  scheduled_type: string;
  notes?: string;
  created_at: string;
  updated_at: string;
  id: string;
  schedulable_id?: string;
  scheduled_at?: string;
  scheduled_time_set: boolean;
}


export interface Task {
  title?: string;
  status?: number;
  position?: number;
  created_at: string;
  updated_at: string;
  subtasks_count?: number;
  reordered_at?: string;
  lock_version: number;
  applies_to_all_targets: boolean;
  id: string;
  job_id?: string;
  assigned_to_id?: string;
  parent_id?: string;
  deleted_at?: string;
}


export interface TaskCompletion {
  status: string;
  completed_at?: string;
  notes?: string;
  created_at: string;
  updated_at: string;
  id: string;
  task_id?: string;
  job_target_id?: string;
  completed_by_id?: string;
}


export interface User {
  name?: string;
  email?: string;
  role?: number;
  created_at: string;
  updated_at: string;
  password_digest?: string;
  resort_tasks_on_status_change: boolean;
  id: string;
}


// Union types for easier usage
export type TableNames = 'activity_logs' | 'contact_methods' | 'jobs' | 'clients' | 'devices' | 'job_assignments' | 'job_people' | 'job_targets' | 'notes' | 'people' | 'scheduled_date_time_users' | 'scheduled_date_times' | 'tasks' | 'task_completions' | 'users';
export type ModelNames = 'activity_log' | 'contact_method' | 'job' | 'client' | 'device' | 'job_assignment' | 'job_person' | 'job_target' | 'note' | 'person' | 'scheduled_date_time_user' | 'scheduled_date_time' | 'task' | 'task_completion' | 'user';
