alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

envs:
  - key: RAILS_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: SECRET_KEY_BASE
    scope: RUN_AND_BUILD_TIME
    value: ${APP_SECRET_KEY_BASE}
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_DATABASE_URL}

features:
  - buildpack-stack=ubuntu-22

ingress:
  rules:
    - component:
        name: bos-backend
      match:
        path:
          prefix: /api
    - component:
        name: bos-frontend
      match:
        path:
          prefix: /

name: bos-staging
region: sgp

services:
  - name: bos-backend
    http_port: 3000
    image:
      registry: richardfaultless
      registry_type: DOCKER_HUB
      repository: rails-api
      tag: latest
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

  - name: bos-frontend
    http_port: 80
    image:
      registry: richardfaultless
      registry_type: DOCKER_HUB
      repository: svelte-frontend
      tag: latest
    instance_count: 2
    instance_size_slug: apps-s-1vcpu-1gb
