alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

envs:
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${DB_HOST}
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    value: ${DB_NAME}
  - key: DB_USER
    scope: RUN_AND_BUILD_TIME
    value: ${DB_USER}
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${DB_PASSWORD}
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${DB_PORT}
  - key: DB_SSLMODE
    scope: RUN_AND_BUILD_TIME
    value: require
  - key: RAILS_ENV
    scope: RUN_AND_BUILD_TIME
    value: production

features:
  - buildpack-stack=ubuntu-22

ingress:
  rules:
    - component:
        name: bos-backend
      match:
        path:
          prefix: /api
    - component:
        name: bos-frontend
      match:
        path:
          prefix: /

name: bos-staging
region: sgp

services:
  - name: bos-backend
    http_port: 3000
    image:
      registry: ${{ secrets.DOCKERHUB_USERNAME }}
      registry_type: DOCKER_HUB
      repository: rails-api
      tag: latest
    instance_count: 2
    instance_size_slug: apps-s-1vcpu-1gb
    envs:
      - key: RAILS_MASTER_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${RAILS_MASTER_KEY}

  - name: bos-frontend
    http_port: 80
    image:
      registry: ${{ secrets.DOCKERHUB_USERNAME }}
      registry_type: DOCKER_HUB
      repository: svelte-frontend
      tag: latest
    instance_count: 2
    instance_size_slug: apps-s-1vcpu-1gb
