// 🤖 AUTO-GENERATED LOGGABLE CONFIGURATION
//
// ⚠️  DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated by Rails generator
// Run: rails generate zero:active_models

export const LOGGABLE_MODELS = {
  // Models with Loggable will be listed here
} as const;

export type LoggableModelName = keyof typeof LOGGABLE_MODELS;

export function isLoggableModel(tableName: string): tableName is LoggableModelName {
  return tableName in LOGGABLE_MODELS;
}

export function getLoggableModelInfo(tableName: LoggableModelName) {
  return LOGGABLE_MODELS[tableName];
}
