/**
 * Epic-008 Model Index - Simplified ActiveRecord/ReactiveRecord Architecture
 *
 * Generated: 2025-07-26 05:25:03 UTC
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To regenerate: rails generate zero:active_models
 */

// Imports for object construction
import { Client } from './client';
import { ReactiveClient } from './reactive-client';

// ActiveRecord models (non-reactive, Promise-based)
export { Client, type ClientData, type CreateClientData, type UpdateClientData } from './client';

// ReactiveRecord models (Svelte 5 reactive)
export { ReactiveClient } from './reactive-client';

/**
 * ActiveRecord models object for dynamic access
 *
 * @example
 * ```typescript
 * import { ActiveModels } from '$lib/models';
 * const Task = ActiveModels.Task;
 * const tasks = await Task.all().all();
 * ```
 */
export const ActiveModels = {
  Client,
};

/**
 * ReactiveRecord models object for dynamic access
 *
 * @example
 * ```typescript
 * import { ReactiveModels } from '$lib/models';
 * const ReactiveTask = ReactiveModels.ReactiveTask;
 * const tasksQuery = ReactiveTask.all().all();
 * ```
 */
export const ReactiveModels = {
  ReactiveClient,
};

/**
 * Import alias helpers for easy switching
 *
 * @example
 * ```typescript
 * // In non-reactive context
 * import { Task } from '$lib/models/task';
 *
 * // In Svelte component
 * import { ReactiveTask as Task } from '$lib/models/reactive-task';
 * ```
 */
