/**
 * Epic-008 Model Index - Simplified ActiveRecord/ReactiveRecord Architecture
 * 
 * Generated: 2025-07-14 12:50:06 UTC
 * 
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To regenerate: rails generate zero:active_models
 */

// ActiveRecord models (non-reactive, Promise-based)
export { User, type UserData, type CreateUserData, type UpdateUserData } from './user';

// ReactiveRecord models (Svelte 5 reactive)
export { ReactiveUser } from './reactive-user';

/**
 * ActiveRecord models object for dynamic access
 * 
 * @example
 * ```typescript
 * import { ActiveModels } from '$lib/models';
 * const Task = ActiveModels.Task;
 * const tasks = await Task.all().all();
 * ```
 */
export const ActiveModels = {
  User
};

/**
 * ReactiveRecord models object for dynamic access
 * 
 * @example
 * ```typescript
 * import { ReactiveModels } from '$lib/models';
 * const ReactiveTask = ReactiveModels.ReactiveTask;
 * const tasksQuery = ReactiveTask.all().all();
 * ```
 */
export const ReactiveModels = {
  ReactiveUser
};

/**
 * Import alias helpers for easy switching
 * 
 * @example
 * ```typescript
 * // In non-reactive context
 * import { Task } from '$lib/models/task';
 * 
 * // In Svelte component
 * import { ReactiveTask as Task } from '$lib/models/reactive-task';
 * ```
 */
