name: bos
description: "AI-Trackdown software project: bos"
version: 1.0.0
tasks_directory: tasks
structure:
  epics_dir: epics
  issues_dir: issues
  tasks_dir: tasks
  templates_dir: templates
  prs_dir: prs
naming_conventions:
  epic_prefix: EP
  issue_prefix: ISS
  task_prefix: TSK
  pr_prefix: PR
  file_extension: .md
default_assignee: claude
ai_context_templates:
  - context/requirements
  - context/constraints
  - context/assumptions
  - context/dependencies
automation:
  auto_update_timestamps: true
  auto_calculate_tokens: false
  auto_sync_status: true
