// 🤖 AUTO-GENERATED ZERO MUTATIONS
// Generated at: 2025-07-11T08:03:40Z
//
// ⚠️  DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated. Manual changes will be overwritten.
//
// 🔧 FOR CUSTOMIZATIONS:
// Use the corresponding .custom.ts file for your custom mutations
//
// 🔄 TO REGENERATE: Run `rails generate zero:mutations`


import { getZero } from '../zero-client';
import { ReactiveQuery, ReactiveQueryOne } from '../reactive-query.svelte';

// Generated TypeScript types for scheduled_date_times
// TypeScript interfaces for scheduled_date_times

/**
 * Complete ScheduledDateTime record as stored in database
 */
export interface ScheduledDateTime {
  schedulable_type: string;
  scheduled_type: string;
  notes?: string| null;
  created_at: number;
  updated_at: number;
  id: string;
  schedulable_id?: string| null;
  scheduled_at?: number| null;
  scheduled_time_set: boolean;
}

/**
 * Data required to create a new scheduled_date_time
 * Excludes auto-generated fields (id, created_at, updated_at)
 */
export interface CreateScheduledDateTimeData {
  schedulable_type: string;
  scheduled_type: string;
  notes?: string| null;
  schedulable_id?: string| null;
  scheduled_at?: number| null;
  scheduled_time_set: boolean;
}

/**
 * Data for updating an existing scheduled_date_time
 * All fields optional, excludes auto-managed fields
 */
export interface UpdateScheduledDateTimeData {
  schedulable_type?: string;
  scheduled_type?: string;
  notes?: string| null;
  schedulable_id?: string| null;
  scheduled_at?: number| null;
  scheduled_time_set?: boolean;
}

/**
 * Standard response from mutation operations
 */
export interface ScheduledDateTimeMutationResult {
  id: string;
}


// Generated CRUD mutations for scheduled_date_times

/**
 * Create a new scheduled_date_time
 * 
 * @param data - The scheduled_date_time data to create
 * @returns Promise resolving to the created scheduled_date_time ID
 * 
 * @example
 * ```typescript
 * import { createScheduledDateTime } from './scheduled_date_time';
 * 
 * const result = await createScheduledDateTime({
 *   // Add required fields here based on your schema
 * });
 * console.log('Created scheduled_date_time with ID:', result.id);
 * ```
 */
export async function createScheduledDateTime(data: CreateScheduledDateTimeData): Promise<ScheduledDateTimeMutationResult> {
  const zero = getZero();
  
  // Validate required fields
  if (!data.schedulable_type?.trim()) throw new Error('Schedulable type is required');
  if (!data.scheduled_type?.trim()) throw new Error('Scheduled type is required');
  if (data.scheduled_time_set === undefined || data.scheduled_time_set === null) throw new Error('Scheduled time set is required');
  // Generate unique ID with validation
  const id = crypto.randomUUID();
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('Failed to generate valid UUID');
  }

  const now = Date.now();

  try {
    await zero.mutate.scheduled_date_times.insert({
      id,
      ...data,
      created_at: now,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to create scheduled_date_time: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Update an existing scheduled_date_time
 * 
 * @param id - The UUID of the scheduled_date_time to update
 * @param data - Partial scheduled_date_time data for updates
 * @returns Promise resolving to the updated scheduled_date_time ID
 * 
 * @example
 * ```typescript
 * import { updateScheduledDateTime } from './scheduled_date_time';
 * 
 * const result = await updateScheduledDateTime('123e4567-e89b-12d3-a456-426614174000', {
 *   // Add fields to update
 * });
 * console.log('Updated scheduled_date_time:', result.id);
 * ```
 */
export async function updateScheduledDateTime(id: string, data: UpdateScheduledDateTimeData): Promise<ScheduledDateTimeMutationResult> {
  const zero = getZero();
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('ScheduledDateTime ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('ScheduledDateTime ID must be a valid UUID');
  }

  // Validate that we have some data to update
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Update data is required - at least one field must be provided');
  }

  const now = Date.now();

  try {
    await zero.mutate.scheduled_date_times.update({
      id,
      ...data,
      updated_at: now,
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to update scheduled_date_time: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Delete a scheduled_date_time (permanent deletion)
 * 
 * @param id - The UUID of the scheduled_date_time to delete
 * @returns Promise resolving to the deleted scheduled_date_time ID
 * 
 * @example
 * ```typescript
 * import { deleteScheduledDateTime } from './scheduled_date_time';
 * 
 * const result = await deleteScheduledDateTime('123e4567-e89b-12d3-a456-426614174000');
 * console.log('Deleted scheduled_date_time:', result.id);
 * ```
 * 
 * @warning This is a permanent deletion and cannot be undone
 */
export async function deleteScheduledDateTime(id: string): Promise<ScheduledDateTimeMutationResult> {
  const zero = getZero();
  
  // Validate ID format
  if (!id || typeof id !== 'string') {
    throw new Error('ScheduledDateTime ID is required and must be a string');
  }
  
  if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
    throw new Error('ScheduledDateTime ID must be a valid UUID');
  }

  try {
    await zero.mutate.scheduled_date_times.delete({
      id
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to delete scheduled_date_time: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


/**
 * Create or update a scheduled_date_time (upsert operation)
 * 
 * @param data - The scheduled_date_time data with optional ID for update, without ID for create
 * @returns Promise resolving to the scheduled_date_time ID (generated if creating, provided if updating)
 * 
 * @example
 * ```typescript
 * import { upsertScheduledDateTime } from './scheduled_date_time';
 * 
 * // Create new scheduled_date_time (no ID provided)
 * const newResult = await upsertScheduledDateTime({
 *   // Add required fields here
 * });
 * 
 * // Update existing scheduled_date_time (ID provided)
 * const updateResult = await upsertScheduledDateTime({
 *   id: '123e4567-e89b-12d3-a456-426614174000',
 *   // Add fields to update
 * });
 * ```
 */
export async function upsertScheduledDateTime(data: (CreateScheduledDateTimeData & { id?: string }) | (UpdateScheduledDateTimeData & { id: string })): Promise<ScheduledDateTimeMutationResult> {
  const zero = getZero();
  
  // Validate data is provided
  if (!data || Object.keys(data).length === 0) {
    throw new Error('Upsert data is required');
  }

  let id: string;
  const now = Date.now();

  // If ID is provided, validate it for update operation
  if (data.id) {
    if (!data.id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('ScheduledDateTime ID must be a valid UUID');
    }
    id = data.id;
  } else {
    // Generate new ID for create operation
    id = crypto.randomUUID();
    if (!id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new Error('Failed to generate valid UUID');
    }
  }

  try {
    await zero.mutate.scheduled_date_times.upsert({
      ...data,
      id,
      updated_at: now,
      // Set created_at only if this is a new record
      ...(data.id ? {} : { created_at: now }),
    });

    return { id };
  } catch (error) {
    throw new Error(`Failed to upsert scheduled_date_time: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}


// Generated ActiveRecord-style queries for scheduled_date_times

/**
 * ActiveRecord-style query interface for scheduled_date_times
 * Provides offline-capable queries that work with Zero's local database
 */
export const ScheduledDateTime = {
  /**
   * Find a single scheduled_date_time by ID
   * @param id - The UUID of the scheduled_date_time
   * @returns Zero query result with the scheduled_date_time or null
   * 
   * @example
   * ```typescript
   * const scheduled_date_time = ScheduledDateTime.find('123e4567-e89b-12d3-a456-426614174000');
   * console.log(scheduled_date_time.current); // The scheduled_date_time object or null
   * ```
   */
  find(id: string) {
    return new ReactiveQueryOne<ScheduledDateTime>(
      () => {
        const zero = getZero();
        return zero ? zero.query.scheduled_date_times.where('id', id).one() : null;
      },
      null
    );
  },

  /**
   * Get all scheduled_date_times
   * @returns Zero query result with array of scheduled_date_times
   * 
   * @example
   * ```typescript
   * const allScheduledDateTimes = ScheduledDateTime.all();
   * console.log(allScheduledDateTimes.current); // Array of scheduled_date_times
   * ```
   */
  all() {
    return new ReactiveQuery<ScheduledDateTime>(
      () => {
        const zero = getZero();
        return zero ? zero.query.scheduled_date_times.orderBy('created_at', 'desc') : null;
      },
      []
    );
  },

  /**
   * Find scheduled_date_times matching conditions
   * @param conditions - Object with field/value pairs to match
   * @returns Zero query result with array of matching scheduled_date_times
   * 
   * @example
   * ```typescript
   * const activeScheduledDateTimes = ScheduledDateTime.where({ status: 'active' });
   * const clientJobs = ScheduledDateTime.where({ client_id: 'some-uuid' });
   * ```
   */
  where(conditions: Partial<ScheduledDateTime>) {
    return new ReactiveQuery<ScheduledDateTime>(
      () => {
        const zero = getZero();
        if (!zero) return null;
        
        let query = zero.query.scheduled_date_times;
        
        Object.entries(conditions).forEach(([key, value]) => {
          if (value !== undefined && value !== null) {
            query = query.where(key, value);
          }
        });
        
        return query.orderBy('created_at', 'desc');
      },
      []
    );
  }
};

