/**
 * ActivityLogData - TypeScript interface for activity_logs table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete ActivityLog record interface
 * Matches the database schema exactly with optional relationships
 */
export interface ActivityLogData extends BaseRecord {
  action?: string;
  loggable_type: string;
  metadata?: Record<string, unknown>;
  created_at: string | number;
  updated_at: string | number;
  id: string;
  user_id?: string;
  client_id?: string;
  job_id?: string;
  loggable_id?: string;
}

/**
 * Create ActivityLog data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateActivityLogData = Omit<ActivityLogData, 'id', 'created_at', 'updated_at'>;

/**
 * Update ActivityLog data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateActivityLogData = Partial<
  Omit<ActivityLogData, 'id', 'created_at', 'updated_at'>
>;
