/**
 * ClientData - TypeScript interface for clients table
 * 
 * Generated from Rails schema: 2025-07-15 22:09:11 UTC
 * 
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete Client record interface
 * Matches the database schema exactly
 */
export interface ClientData extends BaseRecord {
  name?: string;
  created_at: string | number;
  updated_at: string | number;
  name_normalized?: string;
  id: string;
  client_type: 'residential' | 'business';
}

/**
 * Create Client data interface
 * Excludes auto-generated fields
 */
export type CreateClientData = Omit<ClientData, 'id' | 'created_at' | 'updated_at'>;

/**
 * Update Client data interface
 * All fields optional except id
 */
export type UpdateClientData = Partial<Omit<ClientData, 'id' | 'created_at' | 'updated_at'>>;
