/**
 * ClientsFrontConversationData - TypeScript interface for clients_front_conversations table
 *
 * Generated from Rails schema: 2025-08-04 22:23:45 UTC
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete ClientsFrontConversation record interface
 * Matches the database schema exactly with optional relationships
 */
export interface ClientsFrontConversationData extends BaseRecord {
  id: string;
  client_id: string;
  front_conversation_id: string;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create ClientsFrontConversation data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateClientsFrontConversationData = Omit<
  ClientsFrontConversationData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update ClientsFrontConversation data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateClientsFrontConversationData = Partial<
  Omit<ClientsFrontConversationData, 'id', 'created_at', 'updated_at'>
>;
