/**
 * ClientData - TypeScript interface for clients table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete Client record interface
 * Matches the database schema exactly with optional relationships
 */
export interface ClientData extends BaseRecord {
  name?: string;
  created_at: string | number;
  updated_at: string | number;
  name_normalized?: string;
  id: string;
  client_type: 'residential' | 'business';
}

/**
 * Create Client data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateClientData = Omit<ClientData, 'id', 'created_at', 'updated_at'>;

/**
 * Update Client data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateClientData = Partial<Omit<ClientData, 'id', 'created_at', 'updated_at'>>;
