/**
 * ContactMethodData - TypeScript interface for contact_methods table
 *
 * Generated from Rails schema: 2025-07-27 00:18:37 UTC
 * * Relationships (loaded via includes()):
 * - person: belongs_to Person
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';
import type { PersonData } from './person-data';

/**
 * Complete ContactMethod record interface
 * Matches the database schema exactly with optional relationships
 */
export interface ContactMethodData extends BaseRecord {
  value?: string;
  formatted_value?: string;
  created_at: string | number;
  updated_at: string | number;
  id: string;
  person_id?: string;
  contact_type: 'phone' | 'email' | 'address';
  person?: PersonData; // belongs_to
}

/**
 * Create ContactMethod data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateContactMethodData = Omit<
  ContactMethodData,
  'id',
  'created_at',
  'updated_at',
  'person'
>;

/**
 * Update ContactMethod data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateContactMethodData = Partial<
  Omit<ContactMethodData, 'id', 'created_at', 'updated_at', 'person'>
>;
