/**
 * DeviceData - TypeScript interface for devices table
 * 
 * Generated from Rails schema: 2025-07-14 15:26:09 UTC
 * 
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete Device record interface
 * Matches the database schema exactly
 */
export interface DeviceData extends BaseRecord {
  name?: string;
  model?: string;
  serial_number?: string;
  location?: string;
  notes?: string;
  created_at: string | number;
  updated_at: string | number;
  id: string;
  client_id?: string;
  person_id?: string;
}

/**
 * Create Device data interface
 * Excludes auto-generated fields
 */
export type CreateDeviceData = Omit<DeviceData, 'id' | 'created_at' | 'updated_at'>;

/**
 * Update Device data interface
 * All fields optional except id
 */
export type UpdateDeviceData = Partial<Omit<DeviceData, 'id' | 'created_at' | 'updated_at'>>;
