/**
 * DeviceData - TypeScript interface for devices table
 * 
 * Generated from Rails schema: 2025-07-22 01:34:36 UTC
 * * Relationships (loaded via includes()):
 * - client: belongs_to Client
 * - person: belongs_to Person
 * - activityLogs: has_many ActivityLog
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';
import type { ClientData } from './client-data';
import type { PersonData } from './person-data';
import type { ActivityLogData } from './activity-log-data';

/**
 * Complete Device record interface
 * Matches the database schema exactly with optional relationships
 */
export interface DeviceData extends BaseRecord {
  name?: string;
  model?: string;
  serial_number?: string;
  location?: string;
  notes?: string;
  created_at: string | number;
  updated_at: string | number;
  id: string;
  client_id?: string;
  person_id?: string;

  // Epic-011: Relationship properties (optional - loaded via includes())
  client?: ClientData; // belongs_to
  person?: PersonData; // belongs_to
  activityLogs?: ActivityLogData[]; // has_many
}

/**
 * Create Device data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateDeviceData = Omit<DeviceData, 'id' | 'created_at' | 'updated_at' | 'client' | 'person' | 'activityLogs'>;

/**
 * Update Device data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateDeviceData = Partial<Omit<DeviceData, 'id' | 'created_at' | 'updated_at' | 'client' | 'person' | 'activityLogs'>>;
