/**
 * GoodJobExecutionData - TypeScript interface for good_job_executions table
 *
 * Generated from Rails schema: 2025-08-05 22:30:27 UTC
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete GoodJobExecution record interface
 * Matches the database schema exactly with optional relationships
 */
export interface GoodJobExecutionData extends BaseRecord {
  id: string;
  created_at: string | number;
  updated_at: string | number;
  active_job_id: string;
  job_class?: string;
  queue_name?: string;
  serialized_params?: Record<string, unknown>;
  scheduled_at?: string | number;
  finished_at?: string | number;
  error?: string;
  error_event?: number;
  error_backtrace?: string;
  process_id?: string;
  duration?: unknown;
}

/**
 * Create GoodJobExecution data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateGoodJobExecutionData = Omit<
  GoodJobExecutionData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update GoodJobExecution data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateGoodJobExecutionData = Partial<
  Omit<GoodJobExecutionData, 'id', 'created_at', 'updated_at'>
>;
