/**
 * GoodJobBatchData - TypeScript interface for good_job_batches table
 *
 * Generated from Rails schema: 2025-08-05 22:30:27 UTC
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete GoodJobBatch record interface
 * Matches the database schema exactly with optional relationships
 */
export interface GoodJobBatchData extends BaseRecord {
  id: string;
  created_at: string | number;
  updated_at: string | number;
  description?: string;
  serialized_properties?: Record<string, unknown>;
  on_finish?: string;
  on_success?: string;
  on_discard?: string;
  callback_queue_name?: string;
  callback_priority?: number;
  enqueued_at?: string | number;
  discarded_at?: string | number;
  finished_at?: string | number;
  jobs_finished_at?: string | number;
}

/**
 * Create GoodJobBatch data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateGoodJobBatchData = Omit<GoodJobBatchData, 'id', 'created_at', 'updated_at'>;

/**
 * Update GoodJobBatch data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateGoodJobBatchData = Partial<
  Omit<GoodJobBatchData, 'id', 'created_at', 'updated_at'>
>;
