/**
 * GoodJobSettingData - TypeScript interface for good_job_settings table
 *
 * Generated from Rails schema: 2025-08-05 22:30:27 UTC
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete GoodJobSetting record interface
 * Matches the database schema exactly with optional relationships
 */
export interface GoodJobSettingData extends BaseRecord {
  id: string;
  created_at: string | number;
  updated_at: string | number;
  key?: string;
  value?: Record<string, unknown>;
}

/**
 * Create GoodJobSetting data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateGoodJobSettingData = Omit<GoodJobSettingData, 'id', 'created_at', 'updated_at'>;

/**
 * Update GoodJobSetting data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateGoodJobSettingData = Partial<
  Omit<GoodJobSettingData, 'id', 'created_at', 'updated_at'>
>;
