/**
 * GoodJobProcessData - TypeScript interface for good_job_processes table
 *
 * Generated from Rails schema: 2025-08-05 22:30:27 UTC
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete GoodJobProcess record interface
 * Matches the database schema exactly with optional relationships
 */
export interface GoodJobProcessData extends BaseRecord {
  id: string;
  created_at: string | number;
  updated_at: string | number;
  state?: Record<string, unknown>;
  lock_type?: number;
}

/**
 * Create GoodJobProcess data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateGoodJobProcessData = Omit<GoodJobProcessData, 'id', 'created_at', 'updated_at'>;

/**
 * Update GoodJobProcess data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateGoodJobProcessData = Partial<
  Omit<GoodJobProcessData, 'id', 'created_at', 'updated_at'>
>;
