/**
 * GoodJobData - TypeScript interface for good_jobs table
 *
 * Generated from Rails schema: 2025-08-05 22:30:27 UTC
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete GoodJob record interface
 * Matches the database schema exactly with optional relationships
 */
export interface GoodJobData extends BaseRecord {
  id: string;
  queue_name?: string;
  priority?: number;
  serialized_params?: Record<string, unknown>;
  scheduled_at?: string | number;
  performed_at?: string | number;
  finished_at?: string | number;
  error?: string;
  created_at: string | number;
  updated_at: string | number;
  active_job_id?: string;
  concurrency_key?: string;
  cron_key?: string;
  retried_good_job_id?: string;
  cron_at?: string | number;
  batch_id?: string;
  batch_callback_id?: string;
  is_discrete?: boolean;
  executions_count?: number;
  job_class?: string;
  error_event?: number;
  labels?: string;
  locked_by_id?: string;
  locked_at?: string | number;
}

/**
 * Create GoodJob data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateGoodJobData = Omit<GoodJobData, 'id', 'created_at', 'updated_at'>;

/**
 * Update GoodJob data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateGoodJobData = Partial<Omit<GoodJobData, 'id', 'created_at', 'updated_at'>>;
