/**
 * JobTargetData - TypeScript interface for job_targets table
 * 
 * Generated from Rails schema: 2025-07-14 20:18:46 UTC
 * 
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete JobTarget record interface
 * Matches the database schema exactly
 */
export interface JobTargetData extends BaseRecord {
  target_type: string;
  status?: string;
  instance_number: number;
  reason?: string;
  created_at: string | number;
  updated_at: string | number;
  id: string;
  job_id?: string;
  target_id?: string;
}

/**
 * Create JobTarget data interface
 * Excludes auto-generated fields
 */
export type CreateJobTargetData = Omit<JobTargetData, 'id' | 'created_at' | 'updated_at'>;

/**
 * Update JobTarget data interface
 * All fields optional except id
 */
export type UpdateJobTargetData = Partial<Omit<JobTargetData, 'id' | 'created_at' | 'updated_at'>>;
