/**
 * JobPersonData - TypeScript interface for job_people table
 * 
 * Generated from Rails schema: 2025-07-15 02:54:59 UTC
 * 
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete JobPerson record interface
 * Matches the database schema exactly
 */
export interface JobPersonData extends BaseRecord {
  created_at: string | number;
  updated_at: string | number;
  id: string;
  job_id?: string;
  person_id?: string;
}

/**
 * Create JobPerson data interface
 * Excludes auto-generated fields
 */
export type CreateJobPersonData = Omit<JobPersonData, 'id' | 'created_at' | 'updated_at'>;

/**
 * Update JobPerson data interface
 * All fields optional except id
 */
export type UpdateJobPersonData = Partial<Omit<JobPersonData, 'id' | 'created_at' | 'updated_at'>>;
