/**
 * JobPersonData - TypeScript interface for job_people table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete JobPerson record interface
 * Matches the database schema exactly with optional relationships
 */
export interface JobPersonData extends BaseRecord {
  created_at: string | number;
  updated_at: string | number;
  id: string;
  job_id?: string;
  person_id?: string;
}

/**
 * Create JobPerson data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateJobPersonData = Omit<JobPersonData, 'id', 'created_at', 'updated_at'>;

/**
 * Update JobPerson data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateJobPersonData = Partial<Omit<JobPersonData, 'id', 'created_at', 'updated_at'>>;
