/**
 * JobData - TypeScript interface for jobs table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete Job record interface
 * Matches the database schema exactly with optional relationships
 */
export interface JobData extends BaseRecord {
  title?: string;
  created_at: string | number;
  updated_at: string | number;
  description?: string;
  lock_version: number;
  id: string;
  client_id?: string;
  due_at?: string | number;
  due_time_set: boolean;
  starts_at?: string | number;
  start_time_set: boolean;
  status:
    | 'open'
    | 'in_progress'
    | 'paused'
    | 'waiting_for_customer'
    | 'waiting_for_scheduled_appointment'
    | 'successfully_completed'
    | 'cancelled';
  priority: 'critical' | 'very_high' | 'high' | 'normal' | 'low' | 'proactive_followup';
}

/**
 * Create Job data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateJobData = Omit<JobData, 'id', 'created_at', 'updated_at'>;

/**
 * Update Job data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateJobData = Partial<Omit<JobData, 'id', 'created_at', 'updated_at'>>;
