/**
 * JobAssignmentData - TypeScript interface for job_assignments table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete JobAssignment record interface
 * Matches the database schema exactly with optional relationships
 */
export interface JobAssignmentData extends BaseRecord {
  created_at: string | number;
  updated_at: string | number;
  id: string;
  job_id?: string;
  user_id?: string;
}

/**
 * Create JobAssignment data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateJobAssignmentData = Omit<JobAssignmentData, 'id', 'created_at', 'updated_at'>;

/**
 * Update JobAssignment data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateJobAssignmentData = Partial<
  Omit<JobAssignmentData, 'id', 'created_at', 'updated_at'>
>;
