/**
 * NoteData - TypeScript interface for notes table
 * 
 * Generated from Rails schema: 2025-07-23 20:58:14 UTC
 * * Relationships (loaded via includes()):
 * - user: belongs_to User
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';
import type { UserData } from './user-data';

/**
 * Complete Note record interface
 * Matches the database schema exactly with optional relationships
 */
export interface NoteData extends BaseRecord {
  notable_type: string;
  content?: string;
  created_at: string | number;
  updated_at: string | number;
  metadata?: any;
  id: string;
  user_id?: string;
  notable_id?: string;

  // Epic-011: Relationship properties (optional - loaded via includes())
  user?: UserData; // belongs_to
}

/**
 * Create Note data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateNoteData = Omit<NoteData, 'id' | 'created_at' | 'updated_at' | 'user'>;

/**
 * Update Note data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateNoteData = Partial<Omit<NoteData, 'id' | 'created_at' | 'updated_at' | 'user'>>;
