/**
 * NoteData - TypeScript interface for notes table
 * 
 * Generated from Rails schema: 2025-07-16 00:44:52 UTC
 * 
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete Note record interface
 * Matches the database schema exactly
 */
export interface NoteData extends BaseRecord {
  notable_type: string;
  content?: string;
  created_at: string | number;
  updated_at: string | number;
  metadata?: any;
  id: string;
  user_id?: string;
  notable_id?: string;
}

/**
 * Create Note data interface
 * Excludes auto-generated fields
 */
export type CreateNoteData = Omit<NoteData, 'id' | 'created_at' | 'updated_at'>;

/**
 * Update Note data interface
 * All fields optional except id
 */
export type UpdateNoteData = Partial<Omit<NoteData, 'id' | 'created_at' | 'updated_at'>>;
