/**
 * PersonData - TypeScript interface for people table
 * 
 * Generated from Rails schema: 2025-07-14 15:26:09 UTC
 * 
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete Person record interface
 * Matches the database schema exactly
 */
export interface PersonData extends BaseRecord {
  name?: string;
  notes?: string;
  created_at: string | number;
  updated_at: string | number;
  id: string;
  client_id?: string;
}

/**
 * Create Person data interface
 * Excludes auto-generated fields
 */
export type CreatePersonData = Omit<PersonData, 'id' | 'created_at' | 'updated_at'>;

/**
 * Update Person data interface
 * All fields optional except id
 */
export type UpdatePersonData = Partial<Omit<PersonData, 'id' | 'created_at' | 'updated_at'>>;
