/**
 * PersonData - TypeScript interface for people table
 * 
 * Generated from Rails schema: 2025-07-19 23:12:34 UTC
 * * Relationships (loaded via includes()):
 * - client: belongs_to Client
 * - activityLogs: has_many ActivityLog
 * - contactMethods: has_many ContactMethod
 * - devices: has_many Device
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';
import type { ClientData } from './client-data';
import type { ActivityLogData } from './activity-log-data';
import type { ContactMethodData } from './contact-method-data';
import type { DeviceData } from './device-data';

/**
 * Complete Person record interface
 * Matches the database schema exactly with optional relationships
 */
export interface PersonData extends BaseRecord {
  name?: string;
  notes?: string;
  created_at: string | number;
  updated_at: string | number;
  id: string;
  client_id?: string;

  // Epic-011: Relationship properties (optional - loaded via includes())
  client?: ClientData; // belongs_to
  activityLogs?: ActivityLogData[]; // has_many
  contactMethods?: ContactMethodData[]; // has_many
  devices?: DeviceData[]; // has_many
}

/**
 * Create Person data interface
 * Excludes auto-generated fields and relationships
 */
export type CreatePersonData = Omit<PersonData, 'id' | 'created_at' | 'updated_at' | 'client' | 'activityLogs' | 'contactMethods' | 'devices'>;

/**
 * Update Person data interface
 * All fields optional except id, excludes relationships
 */
export type UpdatePersonData = Partial<Omit<PersonData, 'id' | 'created_at' | 'updated_at' | 'client' | 'activityLogs' | 'contactMethods' | 'devices'>>;
