/**
 * PersonData - TypeScript interface for people table
 *
 * Generated from Rails schema: 2025-08-01 20:05:35 UTC
 * * Relationships (loaded via includes()):
 * - client: belongs_to Client
 * - activityLogs: has_many ActivityLog
 * - contactMethods: has_many ContactMethod
 * - devices: has_many Device
 * - notes: has_many Note
 * - peopleGroupMemberships: has_many PeopleGroupMembership
 * - peopleGroups: has_many PeopleGroup, through: people_group_memberships
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';
import type { ClientData } from './client-data';
import type { ActivityLogData } from './activity-log-data';
import type { ContactMethodData } from './contact-method-data';
import type { DeviceData } from './device-data';
import type { NoteData } from './note-data';
import type { PeopleGroupMembershipData } from './people-group-membership-data';
import type { PeopleGroupData } from './people-group-data';

/**
 * Complete Person record interface
 * Matches the database schema exactly with optional relationships
 */
export interface PersonData extends BaseRecord {
  name?: string;
  notes?: string;
  created_at: string | number;
  updated_at: string | number;
  id: string;
  client_id?: string;
  name_preferred?: string;
  name_pronunciation_hint?: string;
  is_active?: boolean;
  title?: string;
  client?: ClientData; // belongs_to
  activityLogs?: ActivityLogData[]; // has_many
  contactMethods?: ContactMethodData[]; // has_many
  devices?: DeviceData[]; // has_many
  notes?: NoteData[]; // has_many
  peopleGroupMemberships?: PeopleGroupMembershipData[]; // has_many
  peopleGroups?: PeopleGroupData[]; // has_many
}

/**
 * Create Person data interface
 * Excludes auto-generated fields and relationships
 */
export type CreatePersonData = Omit<
  PersonData,
  'id',
  'created_at',
  'updated_at',
  'client',
  'activityLogs',
  'contactMethods',
  'devices',
  'notes',
  'peopleGroupMemberships',
  'peopleGroups'
>;

/**
 * Update Person data interface
 * All fields optional except id, excludes relationships
 */
export type UpdatePersonData = Partial<
  Omit<
    PersonData,
    'id',
    'created_at',
    'updated_at',
    'client',
    'activityLogs',
    'contactMethods',
    'devices',
    'notes',
    'peopleGroupMemberships',
    'peopleGroups'
  >
>;
