/**
 * ScheduledDateTimeUserData - TypeScript interface for scheduled_date_time_users table
 * 
 * Generated from Rails schema: 2025-07-15 22:09:11 UTC
 * 
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete ScheduledDateTimeUser record interface
 * Matches the database schema exactly
 */
export interface ScheduledDateTimeUserData extends BaseRecord {
  created_at: string | number;
  updated_at: string | number;
  id: string;
  scheduled_date_time_id?: string;
  user_id?: string;
}

/**
 * Create ScheduledDateTimeUser data interface
 * Excludes auto-generated fields
 */
export type CreateScheduledDateTimeUserData = Omit<ScheduledDateTimeUserData, 'id' | 'created_at' | 'updated_at'>;

/**
 * Update ScheduledDateTimeUser data interface
 * All fields optional except id
 */
export type UpdateScheduledDateTimeUserData = Partial<Omit<ScheduledDateTimeUserData, 'id' | 'created_at' | 'updated_at'>>;
