/**
 * ScheduledDateTimeData - TypeScript interface for scheduled_date_times table
 * 
 * Generated from Rails schema: 2025-07-15 00:18:01 UTC
 * 
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete ScheduledDateTime record interface
 * Matches the database schema exactly
 */
export interface ScheduledDateTimeData extends BaseRecord {
  schedulable_type: string;
  scheduled_type: string;
  notes?: string;
  created_at: string | number;
  updated_at: string | number;
  id: string;
  schedulable_id?: string;
  scheduled_at?: string | number;
  scheduled_time_set: boolean;
}

/**
 * Create ScheduledDateTime data interface
 * Excludes auto-generated fields
 */
export type CreateScheduledDateTimeData = Omit<ScheduledDateTimeData, 'id' | 'created_at' | 'updated_at'>;

/**
 * Update ScheduledDateTime data interface
 * All fields optional except id
 */
export type UpdateScheduledDateTimeData = Partial<Omit<ScheduledDateTimeData, 'id' | 'created_at' | 'updated_at'>>;
