/**
 * TaskData - TypeScript interface for tasks table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete Task record interface
 * Matches the database schema exactly with optional relationships
 */
export interface TaskData extends BaseRecord {
  title?: string;
  position: number;
  created_at: string | number;
  updated_at: string | number;
  subtasks_count?: number;
  reordered_at?: string | number;
  lock_version: number;
  applies_to_all_targets: boolean;
  id: string;
  job_id?: string;
  assigned_to_id?: string;
  parent_id?: string;
  discarded_at?: string | number;
  status: 'new_task' | 'in_progress' | 'paused' | 'successfully_completed' | 'cancelled';
  repositioned_after_id?: string;
  position_finalized: boolean;
  repositioned_to_top: boolean;
}

/**
 * Create Task data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateTaskData = Omit<TaskData, 'id', 'created_at', 'updated_at'>;

/**
 * Update Task data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateTaskData = Partial<Omit<TaskData, 'id', 'created_at', 'updated_at'>>;
