/**
 * TaskCompletionData - TypeScript interface for task_completions table
 * 
 * Generated from Rails schema: 2025-07-15 00:18:01 UTC
 * 
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete TaskCompletion record interface
 * Matches the database schema exactly
 */
export interface TaskCompletionData extends BaseRecord {
  status: string;
  completed_at?: string | number;
  notes?: string;
  created_at: string | number;
  updated_at: string | number;
  id: string;
  task_id?: string;
  job_target_id?: string;
  completed_by_id?: string;
}

/**
 * Create TaskCompletion data interface
 * Excludes auto-generated fields
 */
export type CreateTaskCompletionData = Omit<TaskCompletionData, 'id' | 'created_at' | 'updated_at'>;

/**
 * Update TaskCompletion data interface
 * All fields optional except id
 */
export type UpdateTaskCompletionData = Partial<Omit<TaskCompletionData, 'id' | 'created_at' | 'updated_at'>>;
