/**
 * TaskData - TypeScript interface for tasks table
 * 
 * Generated from Rails schema: 2025-07-15 22:09:11 UTC
 * 
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete Task record interface
 * Matches the database schema exactly
 */
export interface TaskData extends BaseRecord {
  title?: string;
  position?: number;
  created_at: string | number;
  updated_at: string | number;
  subtasks_count?: number;
  reordered_at?: string | number;
  lock_version: number;
  applies_to_all_targets: boolean;
  id: string;
  job_id?: string;
  assigned_to_id?: string;
  parent_id?: string;
  discarded_at?: string | number;
  status: 'new_task' | 'in_progress' | 'paused' | 'successfully_completed' | 'cancelled';
}

/**
 * Create Task data interface
 * Excludes auto-generated fields
 */
export type CreateTaskData = Omit<TaskData, 'id' | 'created_at' | 'updated_at'>;

/**
 * Update Task data interface
 * All fields optional except id
 */
export type UpdateTaskData = Partial<Omit<TaskData, 'id' | 'created_at' | 'updated_at'>>;
