/**
 * UserData - TypeScript interface for users table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete User record interface
 * Matches the database schema exactly with optional relationships
 */
export interface UserData extends BaseRecord {
  name?: string;
  email?: string;
  created_at: string | number;
  updated_at: string | number;
  password_digest?: string;
  resort_tasks_on_status_change: boolean;
  id: string;
  role: 'admin' | 'technician' | 'customer_specialist' | 'owner';
  short_name?: string;
}

/**
 * Create User data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateUserData = Omit<UserData, 'id', 'created_at', 'updated_at'>;

/**
 * Update User data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateUserData = Partial<Omit<UserData, 'id', 'created_at', 'updated_at'>>;
