name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Rails API
      - name: Build & push Rails API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rails-api:latest

      # Build and push Svelte Frontend
      - name: Build & push Svelte Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/svelte-frontend:latest

      # Install doctl
      - name: Install doctl
        run: |
          sudo snap install doctl --classic

      # Authenticate doctl
      - name: Authenticate doctl
        run: doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # Trigger App Platform deployment
      - name: Deploy to DigitalOcean App Platform
        run: doctl apps update ${{ secrets.DO_APP_ID }} --spec .do/app.yml
