name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Rails API (root folder)
      - name: Build & push Rails API
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rails-api:latest

      # Build and push Svelte Frontend (frontend folder)
      - name: Build & push Svelte Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/svelte-frontend:latest

      # Install doctl (DigitalOcean CLI)
      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.113.0/doctl-1.113.0-linux-amd64.tar.gz \
          | tar -xzv
          sudo mv doctl /usr/local/bin

      # Deploy to DigitalOcean App Platform
      - name: Deploy to DigitalOcean
        run: |
          doctl apps update ${{ secrets.DO_APP_ID }} \
            --spec .do/app.yml \
            --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
